mysql:
  image: mysql:5.6
  container_name: drupal-project_db
  environment:
    MYSQL_ROOT_PASSWORD: rootpasswd
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
  volumes:
    # Volume for db storage.
    -  ./storage/mysql:/var/lib/mysql
  ports:
    - "3306"
web:
  image: tbfisher/drupal-nginx:php-5.6.x
  container_name: drupal-project_web
  ports:
    - "8888:80"
    - "443"
    - "22"
  volumes:
    # Drupal files here.
    - ./docroot/:/var/www
  links:
    - mysql
