mysql:
  image: mysql:5.6
  container_name: CHANGE_ME_db
  environment:
    MYSQL_ROOT_PASSWORD: rootpasswd
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
  volumes:
    # Volume for db storage.
    -  ./storage/mysql:/var/lib/mysql
  ports:
    - "3306"
mail:
  # https://hub.docker.com/r/mailhog/mailhog/
  image: mailhog/mailhog
  container_name: CHANGE_ME_mail
  ports:
   - "1025"
   - "8025"
  environment:
    VIRTUAL_HOST: mail.CHANGE_ME.loc
    VIRTUAL_PORT: 8025
adminer:
  image: clue/adminer
  container_name: CHANGE_ME_adminer
  ports:
   - "80"
  environment:
    VIRTUAL_HOST: adminer.CHANGE_ME.loc
  links:
    - mysql
web:
  build: ./docker/web
  container_name: CHANGE_ME_web
  ports:
    - "80"
    - "443"
    - "22"
  volumes:
    # Drupal files here.
    - ./docroot/:/var/www
    - ./dummyfile:/tmp/dummyfile
  environment:
    VIRTUAL_HOST: CHANGE_ME.loc
  links:
    - mysql
    - mail
